[package]
name = "e310x"
version = "0.9.0"
repository = "https://github.com/riscv-rust/e310x"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "With svd2rust generated peripherals for Freedom E310 MCU's."
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[dependencies]
bare-metal = "1.0.0"
vcell = "0.1.3"
riscv = "0.7.0"

[features]
rt = []
g002 = []

[package.metadata.docs.rs]
features = ["rt", "g002"]
