[package]
name = "e310x-hal"
version = "0.9.3"
authors = ["David Craven <david@craven.ch>"]
repository = "https://github.com/riscv-rust/e310x-hal"
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for the E310x family of microcontrollers."
keywords = ["riscv", "e310", "hal"]
license = "ISC"
edition = "2018"

[dependencies]
embedded-hal = "=1.0.0-alpha.7"
nb = "1.0.0"
riscv = "0.8.0"
e310x = { version = "0.9.0", features = ["rt"] }

[features]
g002 = ["e310x/g002"]

[package.metadata.docs.rs]
features = ["g002"]
