[package]
name = "e310x"
version = "0.4.0"
repository = "https://github.com/riscv-rust/e310x"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "With svd2rust generated peripherals for Freedom E310 MCU's."
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[dependencies]
bare-metal = "0.2.1"
vcell = "0.1.0"
riscv = "0.5.0"
riscv-rt = { version = "0.5.0", optional = true }

[features]
rt = ["riscv-rt"]
g002 = []

[package.metadata.docs.rs]
features = ["rt"]
